# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习\AI\ui\gui_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(527, 510)
        self.textEdit_chat = QtWidgets.QTextEdit(Form)
        self.textEdit_chat.setGeometry(QtCore.QRect(30, 50, 461, 321))
        self.textEdit_chat.setReadOnly(True)
        self.textEdit_chat.setObjectName("textEdit_chat")
        self.lineEdit_input = QtWidgets.QLineEdit(Form)
        self.lineEdit_input.setGeometry(QtCore.QRect(30, 379, 461, 91))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 211, 41))
        self.label.setObjectName("label")
        self.pushButton_send = QtWidgets.QPushButton(Form)
        self.pushButton_send.setGeometry(QtCore.QRect(424, 440, 61, 23))
        self.pushButton_send.setObjectName("pushButton_send")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_input.setPlaceholderText(_translate("Form", "请输入你的问题"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">DeepSeek聊天</span></p></body></html>"))
        self.pushButton_send.setText(_translate("Form", "发送"))
